---
- name: Deploy Docker Image to Container
  hosts: localhost

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: vishalrao7/scientific_calculator
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: Calculator_SPE_mini
        image: vishalrao7/scientific_calculator
        state: started
        tty: yes
        interactive: yes
